import type { StringKey } from './strings';

export const stringsEn: Partial<Record<StringKey, string>> = {
  app_name: 'Mail',
  folder_inbox: 'Inbox',
  folder_starred: 'Starred',
  folder_drafts: 'Drafts',
  folder_sent: 'Sent',
  folder_trash: 'Trash',

  title_mailbox: 'Mailbox',
  title_folders: 'Folders',

  list_default_title: 'Inbox',
  list_empty_inbox: 'Inbox is empty',
  list_empty_starred: 'No starred messages',
  list_empty_drafts: 'No drafts',
  list_empty_sent: 'No sent messages',
  list_empty_trash: 'Trash is empty',
  list_unread_suffix: 'unread',
  list_draft_label: 'Draft',
  list_attachment_indicator: 'Attachment',
  action_mark_all_read: 'Mark all read',
  action_compose: 'Compose',
  action_switch_folder: 'Switch folder',

  detail_label_from: 'From',
  detail_label_to: 'To',
  detail_label_cc: 'Cc',
  detail_label_subject: 'Subject',
  detail_label_attachments: 'Attachments',
  detail_no_subject: '(no subject)',
  detail_draft_badge: 'Draft',
  detail_not_found: 'Message not found',
  action_reply: 'Reply',
  action_forward: 'Forward',
  action_delete: 'Delete',
  action_star: 'Star',
  action_unstar: 'Unstar',
  action_edit: 'Edit',
  action_restore: 'Restore',
  action_move_to_trash_confirm: 'Move this message to Trash?',
  action_delete_forever_confirm: 'Permanently delete this message?',
  confirm_ok: 'OK',
  confirm_cancel: 'Cancel',

  compose_title_new: 'New Message',
  compose_title_edit: 'Edit Draft',
  compose_label_to: 'To',
  compose_label_cc: 'Cc',
  compose_label_subject: 'Subject',
  compose_label_body: 'Body',
  compose_placeholder_recipient: 'Type email or name',
  compose_placeholder_subject: 'Subject',
  compose_placeholder_body: 'Compose your message',
  compose_show_cc: 'Add Cc',
  compose_hide_cc: 'Hide Cc',
  compose_add_attachment: 'Attach',
  compose_button_save_draft: 'Save Draft',
  compose_button_send: 'Send',
  compose_button_discard: 'Discard',
  compose_invalid_recipient_title: 'Invalid Recipient',
  compose_invalid_recipient_body: 'Enter a valid email address or pick one from Contacts.',
  compose_invalid_recipient_ok: 'Got it',
  compose_empty_send_title: 'Cannot Send',
  compose_empty_send_body: 'Please fill in at least one recipient plus a subject or body.',
  compose_empty_send_ok: 'Got it',
  compose_draft_saved_toast: 'Draft saved',
  compose_sent_toast: 'Message sent',
  compose_attachment_copy_failed: 'The attachment could not be copied. Check the source file and try again.',
  attachment_unavailable: 'This attachment is missing or cannot be opened right now.',
  compose_remove_attachment: 'Remove attachment',
  unsaved_changes_title: 'Discard Changes?',
  unsaved_changes_body: 'You have unsaved edits. Discard them?',
  unsaved_changes_discard: 'Discard',
  unsaved_changes_keep: 'Keep Editing',

  attach_panel_title: 'Add Attachment',
  attach_type_image: 'Image',
  attach_type_document: 'Document',
  attach_type_video: 'Video',
  attach_type_audio: 'Audio',
  attach_type_camera: 'Camera',
  attach_type_other: 'File',

  recipient_me: 'Me',
  recipient_unknown: 'Unknown',

  select_file_title: 'Select File',
  empty_file_list: 'No files',

  back: 'Back',
  toast_moved_to_trash: 'Moved to Trash',
  toast_deleted_forever: 'Deleted permanently',
  toast_restored: 'Restored',
  toast_starred: 'Starred',
  toast_unstarred: 'Unstarred',
  toast_marked_read: 'Marked as read',
};

export default stringsEn;
