import type { NavigationDeclaration } from './navigation.types';

const MAIN_SCROLL = [
  { name: 'main', direction: 'vertical', description: '页面主内容区' },
] as const;

export const NAVIGATION_DECLARATION = {
  app: 'mail',
  routes: [
    {
      path: '/',
      component: 'FolderListPage',
      params: {},
      entryPoint: 'home',
      scrollContainers: MAIN_SCROLL,
      uiStates: [
        { id: 'mail.list.base', search: {}, description: '当前文件夹邮件列表页（默认收件箱）' },
        { id: 'mail.list.menu', search: { menu: 'open' }, description: '侧边栏菜单打开', actions: [
          { id: 'menu.folder.switch', label: '切换文件夹', behavior: 'other', scope: 'item', paramsSchema: { folder: 'string' } },
        ] },
      ],
      queryParams: { folder: 'string' },
      description: '当前文件夹邮件列表页',
    },
    {
      path: '/folders',
      component: 'FoldersPage',
      params: {},
      entryPoint: 'none',
      scrollContainers: MAIN_SCROLL,
      uiStates: [{ id: 'mail.folders.base', search: {}, description: '文件夹切换页' }],
      queryParams: {},
      description: '文件夹切换页',
    },
    {
      path: '/message/:messageId',
      component: 'MessageDetailPage',
      params: { messageId: 'string' },
      entryPoint: 'deepLink',
      scrollContainers: MAIN_SCROLL,
      uiStates: [{
        id: 'mail.detail.base',
        search: {},
        description: '邮件详情页',
        actions: [
          {
            id: 'mail.detail.item.open',
            label: '打开邮件附件',
            behavior: 'other',
            scope: 'item',
            paramsSchema: { attachmentId: 'string', fileId: 'string' },
          },
        ],
      }],
      queryParams: {},
      description: '邮件详情页',
    },
    {
      path: '/compose',
      component: 'ComposePage',
      params: {},
      entryPoint: 'both',
      scrollContainers: MAIN_SCROLL,
      uiStates: [{
        id: 'mail.compose.base',
        search: {},
        description: '写新邮件页',
        actions: [
          { id: 'compose.attachment.add', label: '添加附件', behavior: 'other', paramsSchema: { type: 'string' } },
        ],
      }],
      queryParams: { selectFile: 'string', replyId: 'string', forwardId: 'string' },
      description: '写新邮件页',
    },
    {
      path: '/compose/:draftId',
      component: 'ComposePage',
      params: { draftId: 'string' },
      entryPoint: 'none',
      scrollContainers: MAIN_SCROLL,
      uiStates: [{
        id: 'mail.compose.draft.base',
        search: {},
        description: '编辑草稿页',
      }],
      queryParams: { selectFile: 'string' },
      description: '编辑草稿页',
    },
  ],
  transitions: [
    {
      id: 'menu.open',
      from: '/',
      to: '/',
      search: { menu: 'open' },
      searchParams: {},
      preserveParams: ['folder'],
      mode: 'push',
      params: {},
      label: '打开侧边栏菜单',
      ui: { placement: 'topbar', icon: 'menu', gesture: 'tap' },
    },
    {
      id: 'menu.folder.switch',
      from: [{ path: '/', search: { menu: '*' } }],
      to: '/',
      search: { menu: null },
      searchParams: { folder: 'string' },
      mode: 'replace',
      params: { folder: 'string' },
      label: '从侧边栏切换文件夹',
      ui: { placement: 'content', icon: 'folder', gesture: 'tap' },
    },
    {
      id: 'compose.open',
      from: '/',
      to: '/compose',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '打开写邮件页',
      ui: { placement: 'fab', icon: 'add', gesture: 'tap' },
    },
    {
      id: 'folders.open',
      from: '/',
      to: '/folders',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '打开文件夹切换页',
      ui: { placement: 'topbar', icon: 'folders', gesture: 'tap' },
    },
    {
      id: 'folder.switch',
      from: '/folders',
      to: '/',
      search: {},
      searchParams: { folder: 'string' },
      mode: 'replace',
      params: { folder: 'string' },
      label: '切换当前文件夹后回到列表',
      ui: { placement: 'content', icon: 'folder', gesture: 'tap' },
    },
    {
      id: 'message.open',
      from: '/',
      to: '/message/:messageId',
      search: {},
      searchParams: {},
      mode: 'push',
      params: { messageId: 'string' },
      label: '打开邮件详情',
      ui: { placement: 'content', icon: 'mail', gesture: 'tap' },
    },
    {
      id: 'compose.draft.open',
      from: '/message/:messageId',
      to: '/compose/:draftId',
      search: {},
      searchParams: {},
      mode: 'push',
      params: { draftId: 'string' },
      label: '编辑已有草稿',
      ui: { placement: 'content', icon: 'edit', gesture: 'tap' },
    },
    {
      id: 'compose.fromReply',
      from: '/message/:messageId',
      to: '/compose',
      search: {},
      searchParams: { replyId: 'string' },
      mode: 'push',
      params: { replyId: 'string' },
      label: '从详情页发起回复',
      ui: { placement: 'topbar', icon: 'reply', gesture: 'tap' },
    },
    {
      id: 'compose.fromForward',
      from: '/message/:messageId',
      to: '/compose',
      search: {},
      searchParams: { forwardId: 'string' },
      mode: 'push',
      params: { forwardId: 'string' },
      label: '从详情页发起转发',
      ui: { placement: 'topbar', icon: 'forward', gesture: 'tap' },
    },
    {
      id: 'compose.saveDraft',
      from: ['/compose', '/compose/:draftId'],
      to: '/',
      search: {},
      searchParams: {},
      mode: 'replace',
      params: {},
      label: '保存草稿后回到列表',
      ui: { placement: 'topbar', icon: 'edit', gesture: 'tap' },
    },
    {
      id: 'compose.send',
      from: ['/compose', '/compose/:draftId'],
      to: '/message/:messageId',
      search: {},
      searchParams: {},
      mode: 'replace',
      params: { messageId: 'string' },
      label: '发送邮件后进入详情',
      ui: { placement: 'topbar', icon: 'send', gesture: 'tap' },
    },
  ],
  capabilities: {
    historyBack: true,
  },
} as const satisfies NavigationDeclaration;

export type TransitionId = typeof NAVIGATION_DECLARATION.transitions[number]['id'];
