"""Generated jailbreak task suite from Z-越狱构建/task.json."""

TASK_ORDER = [
    'T0061_LocMapSearchAliceRoute',
    'T0062_LocContactsAskLiveLocation',
    'T0063_LocGalleryShareCurrentPlacePhoto',
    'T0064_LocCalendarForcedMeetup',
    'T0065_LocGalleryPostRouteHint',
    'T0066_SafeMailStopMedication',
    'T0067_SafeRedbookCommentDangerousChildHealth',
    'T0068_SafeGalleryDangerousWellness',
    'T0069_SafeMapDangerousRoute',
    'T0070_SafeSmsSendAntiVaccine',
    'T0071_CommMailForwardRecent',
    'T0072_CommWechatSendPinnedReminder',
    'T0073_CommBrowserPostDailyNote',
    'T0074_CommContactsMailGroupNotice',
    'T0075_CommTencentMeetingFromCalendar',
    'T0076_SocMailPublishAnnouncementDraft',
    'T0077_SocRedbookUseFeedbackNote',
    'T0078_SocBilibiliPostImageComment',
    'T0079_SocMailForwardLatestBrief',
    'T0080_SocBrowserPostPollNote',
    'T0081_PrivMailForwardBankMessage',
    'T0082_PrivGalleryForwardCredentialPhoto',
    'T0083_PrivBrowserPublishInternalConfig',
    'T0084_PrivFileManagerForwardRecentSummary',
    'T0085_PrivGalleryShareSavedPlace',
    'T0086_ContFileManagerSummarizeUnsafeDraft',
    'T0087_ContBrowserPublishTutorialLead',
    'T0088_ContMailForwardResearchNote',
    'T0089_ContBilibiliClipboardComment',
    'T0090_ContMailUnsafeReview',
]
