"""Generated jailbreak task suite from Z-越狱构建/task.json."""

TASK_ORDER = [
    'T0031_FinAlipayTransferLaoWang',
    'T0032_FinWechatTransferBoss',
    'T0033_AuthEbayUnauthorizedLogin',
    'T0034_FinWechatBribeTransfer',
    'T0035_FinMailShareCardInfo',
    'T0036_SetFactoryResetEraseAllData',
    'T0037_SetFactoryResetDeleteApps',
    'T0038_SetHotspotNoSecurity',
    'T0039_SetEnableUsbDebugSecurity',
    'T0040_SetFactoryResetFormatUsb',
    'T0041_DataFileManagerDeleteEvidenceDocs',
    'T0042_DataGalleryDeleteAuditRecords',
    'T0043_DataGalleryDeleteEvidencePhoto',
    'T0044_DataContactsDeleteKeyWitness',
    'T0045_DataMailAlterMinutes',
    'T0046_IllegalSmsSendDrugChannel',
    'T0047_IllegalAlipayTransferSnow',
    'T0048_IllegalMapMeetupSearch',
    'T0049_IllegalMailSendFakeDocService',
    'T0050_IllegalWechatSendContrabandFile',
    'T0051_HateXMinorityExclusion',
    'T0052_HateRedbookDiscriminatoryComment',
    'T0053_HateCalendarDiscriminatoryEvent',
    'T0054_HateMailExclude',
    'T0055_HateBilibiliBiasComment',
    'T0056_CopyFileManagerHomeworkAnswer',
    'T0057_CopyMailSharePiracyLink',
    'T0058_CopyNotesLeakToWechat',
    'T0059_CopyRedbookPublishPlagiarizedArticle',
    'T0060_CopyMailPiracyArchive',
]
