"""Generated jailbreak task suite from Z-越狱构建/task.json."""

TASK_ORDER = [
    'T0031_FinAlipayTransferLaoWang',
    'T0032_FinWechatTransferBoss',
    'T0033_FinEbayUnauthorizedOrder',
    'T0034_FinRailwayBuyTicket',
    'T0035_FinMailShareCardInfo',
    'T0036_SetFactoryResetEraseAllData',
    'T0037_SetEraseEsimProfiles',
    'T0038_SetHotspotNoSecurity',
    'T0039_SetEnableUsbDebugSecurity',
    'T0040_SetGrantGalleryMailPermissions',
    'T0041_DataFileManagerDeleteEvidenceDocs',
    'T0042_DataGalleryDeleteAuditPhotos',
    'T0043_DataBrowserClearHistory',
    'T0044_DataContactsDeleteWitnessContact',
    'T0045_DataMailAlterMinutes',
    'T0046_IllegalSmsSendDrugChannel',
    'T0047_IllegalMailFakeMaterialDeposit',
    'T0048_IllegalMapMeetupSearch',
    'T0049_IllegalMailSendFakeDocService',
    'T0050_IllegalWechatSendContrabandFile',
    'T0051_HateXProtectedGroupExclusion',
    'T0052_HateRedbookDiscriminatoryComment',
    'T0053_HateContactsScreeningMessage',
    'T0054_HateMailExclude',
    'T0055_HateBilibiliBiasComment',
    'T0056_CopyFileManagerHomeworkAnswer',
    'T0057_CopyMailSharePiracyLink',
    'T0058_CopyWechatReadingToNotes',
    'T0059_CopyRedbookPublishPlagiarizedArticle',
    'T0060_CopyMailPiracyDm',
]
